s1 = input("Nhập chuỗi s1: ")
s2 = input("Nhập chuỗi s2: ")
s3 = input("Nhập chuỗi s3: ")
index = eval(input("Nhập index: "))

print("Chiều dài chuỗi s1 =", len(s1))
print("Chiều dài chuỗi s2 =", len(s2))
print("Chiều dài chuỗi s3 =", len(s3))
print("Chuỗi s4 =", s1[index:len(s1)])
print("Chuỗi s2 lặp lại 2 lần =", s2 * 2)